### ISSUE TITLE
Deprecate

### ISSUE THREAD

**Issue by uipoet** [uipoet/sublime-jshint#72]
The Sublime Linter (with JSHint plugin) now supports all that sublime-jshint does and more, namely inline column highlighting of lines with errors.

The maintainers of sublime-jshint have decided it's time to step aside and recommend this alternative, making the decision of how to lint JavaScript in Sublime a simpler one.

We'll be updating the Readme.md and removing our source code accordingly.

**Comment by stevage** [comment]
@uipoet Yes, please do. Just spent a while trying to diagnose this error:

```
Sublime Text 3/Packages/JSHint/reporter.js:29
      buffer += numberWang((error.line + error.character.toString()).length) +
                                                        ^
TypeError: Cannot read property 'toString' of undefined
    at /Users/stevebennett/Library/Application Support/Sublime Text 3/Packages/JSHint/reporter.js:29:57
    at Array.forEach (native)
    at exports.reporter (/Users/stevebennett/Library/Application Support/Sublime Text 3/Packages/JSHint/reporter.js:25:12)
    at Object.exports.run (/Users/stevebennett/npm/lib/node_modules/jshint/src/cli.js:654:35)
    at Object.exports.interpret (/Users/stevebennett/npm/lib/node_modules/jshint/src/cli.js:737:18)
    at Object.<anonymous> (/Users/stevebennett/npm/lib/node_modules/jshint/bin/jshint:3:26)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

```

had no idea it was deprecated...

**Comment by kirankoduru** [comment]
@uipoet please update the README. I had the same issue as @stevage mentioned above.
